### PR TITLE
Revised methods, example, and tests for pull request

### PR DESCRIPTION
**Pull request by jbgracey6**
Hi @corybrunson. This commit contains the revised methods for objects of class "psych" "principal" as well as the corresponding example and tests. All tests pass and the example runs smoothly. Please let me know if the results on your end do not agree for any reason or if you see any areas for improvement!

### CODE REVIEW

**Comment by corybrunson** [comment]
@jbgracey6 this looks good. Though it looks like the new functions have not been documented. Have you run `devtools::document()`? You'll also need to add yourself as a package author in DESCRIPTION.

I have trouble with the examples when the associated modeling packages (like {ade4} are not installed. [This conditioning practice](https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-in-examples-and-vignettes) seems to resolve it, so let me branch off main to condition the current examples, merge into `principal`, and then ask you to follow the practice for your examples that use {psych}—hopefully this evening.

**Comment by jbgracey6** [comment]
@corybrunson You're right, I remembered updating the documentation for `princomp()` and thought I'd already done it here as well. I just committed with the up-to-date DESCRIPTION and documented functions.

Also, I read through the page you linked and want to make sure I understand properly. For Suggests like {ade4}, would we want to preface the example script with something like `install.packages(dependencies = "Suggests")`? Or is there a different/standard approach to this?

**Comment by corybrunson** [comment]
Hi @jbgracey6, i've made what i think are the necessary changes to the existing examples and tests and pushed them to `main`. Please
1. merge `main` into `principal`,
2. follow the pattern in the updated examples and tests in those for 'principal',
3. update the documentation again, and
4. push again to GitHub to update this PR.

Thanks for prompting this fix!

**Comment by corybrunson** [comment]
@jbgracey6 also please rename the example file to match the pattern of the other example files (the package name is missing).

**Comment by corybrunson** [comment]
@jbgracey6 please make the following minor fixes, which caused errors during `devtools::check()`:

1. Insert a missing comma in your author credit in 'DESCRIPTION'.
2. Add `psych` to `Suggests:` in 'DESCRIPTION'.
3. Rename the new test file to 'test-psych.R', since it will eventually also include tests for `psych::fa()`.
4. Preface the tests with `skip_if_not_installed()`; see other tests for guidance.
5. Call `psych::principal()` rather than `principal()` in the tests, since the `Suggests` packages are not loaded with the package.

I think that will suffice. You should be able to run the check yourself and only get warnings about missing packages.

**Comment by jbgracey6** [comment]
Hi @corybrunson. I made the edits you listed, but I am running into an error when I run `devtools::check()` that says "could not find function "principal"". Can you let me know whether you encounter the same error on your end, and if so, what might be causing it? Thanks!

**Comment by corybrunson** [comment]
Thanks @jbgracey6 ! Please be sure that items 4 and 5 are covered. At a glance, it seems that 4 is missing from the test file, and that 5 is causing the error (on line 1 of the test file).

**Comment by jbgracey6** [comment]
Ah, my mistake! I forgot to add it to the staging area after making the edit. The changes should all be there now. Thanks @corybrunson!

**Comment by corybrunson** [comment]
I think it looks good! I forgot to ask, though, that you add your author info & credit as in the {ordr} PR.

**Comment by corybrunson** [comment]
My mistake! Looks good now, with some accidentally dropped documentation restored and the unnecessary `@include` tag removed.

**Pull request merged**
